<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>9b8d24ea-2b5f-436d-97c1-a65fecdaa96b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlSanitizer" Version="9.2.995" />
	<PackageReference Include="JoyfulReaperLib.MissionControl" Version="0.0.3" />
	<PackageReference Include="JoyfulReaperLib.Sqlite" Version="0.0.10" />
	<PackageReference Include="JoyfulReaperLib.WebStats.Sqlite" Version="0.0.10" />
	<PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RandomGithub.GitHub\RandomGithub.GitHub.csproj" />
  </ItemGroup>

</Project>
